name: codequest_etr
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background/ # Includes lvl1.jpg, lvl2.jpg, lvl3.jpg, lvl4.jpg
    - assets/characters/ # Includes character images and enemy images (enemy.png, enemy1.png, enemy2.png)

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P.ttf
